site_name: Sandbox Docs
repo_url: https://github.com/adlnet/SandboxDocs
site_favicon: favicon.ico
docs_dir : ./docs
theme: readthedocs
use_directory_urls: true
markdown_extensions: [admonition]
pages:
- ['index.md', 'About']
- ['Home.md', 'Home']
- ['Developer Guide/Developer-Guide.md', 'For Developers']
- ['FAQ.md', 'For Users', 'FAQ']

- ['User Guide/Using-The-Editor.md', 'For Users', 'Using The Editor']
- ['User Guide/Selecting-Objects.md', 'For Users', 'Selecting Objects']
- ['User Guide/Lights and Materials.md', 'For Users', 'Lights and Materials']
- ['User Guide/terrain.md', 'For Users', 'Terrain']
- ['User Guide/Cameras.md', 'For Users', 'Cameras']
- ['User Guide/GUINodes.md', 'For Users', 'GUI Nodes']
- ['User Guide/Physics.md', 'For Users', 'Physics']
- ['User Guide/Particles.md', 'For Users', 'Particles']
- ['User Guide/Assets.md', 'For Users', 'Assets and Models']
- ['User Guide/Phong-Material.md', 'For Users', 'Phong Material']
- ['User Guide/Sharing-the-camera-view.md', 'For Users', 'Sharing the Camera View']
- ['User Guide/User-Guide.md', 'For Users', 'User Guide']
- ['User Guide/Using-The-Editor.md', 'For Users', 'Using the Editor']
- ['User Guide/Working with Groups.md', 'For Users', 'Working with Groups']
- ['User Guide/Working with Terrain.md', 'For Users', 'Working with Terrain']
- ['User Guide/build a game.md', 'For Users', 'Build a Game']

- ['Developer Guide/Installation.md', 'Developer Guide','Installation']
- ['Developer Guide/Configuration.md', 'Developer Guide','Configuration']
- ['Developer Guide/configure 3DR.md', 'Developer Guide','Asset Server']
- ['Developer Guide/Architecture-Overview.md', 'Developer Guide','Architecture Overview']
- ['Developer Guide/Data-Organization.md', 'Developer Guide','Data Organization']
- ['Developer Guide/File-Organization.md', 'Developer Guide','File Organization']
- ['Developer Guide/Development-Plans.md', 'Developer Guide','Development Plans']
- ['Developer Guide/SandboxAPI.md', 'Developer Guide','Sandbox API']
- ['Developer Guide/_3rd-Party-Libraries.md', 'Developer Guide','3rd Party Libraries']
- ['Developer Guide/drivers/Drivers.md', 'Developer Guide','Driver Reference']
- ['Developer Guide/Extending.md', 'Developer Guide','Extending Sandbox']
- ['Developer Guide/Assets.md', 'Developer Guide','Asset Pipeline']
- ['Developer Guide/Prims-and-Modifiers.md', 'Developer Guide','Prim and Modifier Pipeline']
- ['Developer Guide/Asset-Server-Integration.md', 'Developer Guide','Asset and Server Integration']
- ['Developer Guide/Development.md', 'Developer Guide','Development']
- ['Developer Guide/particleSystem.md', 'Developer Guide','Particle Systems']

- ['Scripting/scripting/ScriptingIntro.md', 'Scripting','Introduction to Scripting']
- ['Scripting/scripting/Events.md', 'Scripting','Events']
- ['Scripting/scripting/Behaviors.md', 'Scripting','Behaviors']
- ['Scripting/scripting/Working with Entities.md', 'Scripting','Working with Entities']
- ['Scripting/scripting/Entity Property Reference.md', 'Scripting','Entity Property Reference']
- ['Scripting/scripting/Nodes.md', 'Scripting','Nodes']

- ['SystemAPI/SystemAPIs.md', 'System APIs','System API']
- ['SystemAPI/AudioAPI.md', 'System APIs','Audio API']
- ['SystemAPI/ClientAPI.md', 'System APIs','Client API']
- ['SystemAPI/CommsAPI.md', 'System APIs','Communications API']
- ['SystemAPI/PhysicsAPI.md', 'System APIs','Physics API']
- ['SystemAPI/TransformAPI.md', 'System APIs','Transform API']
