site_name: Sandbox Docs
repo_url: https://github.com/adlnet/SandboxDocs
site_favicon: favicon.ico
docs_dir : ./docs
theme: readthedocs
use_directory_urls: true
markdown_extensions: [admonition]
pages:
- ['index.md', 'About']
- ['Home.md', 'Home']
- ['Developer Guide/Developer-Guide.md', 'For Developers']
- ['User Guide/Basic-Workflow.md', 'For Users']
- ['Developer Guide/Installation.md', 'Developer Guide','Installation']
- ['Developer Guide/Configuration.md', 'Developer Guide','Configuration']
- ['Developer Guide/configure 3DR.md', 'Developer Guide','Asset Server']
- ['Developer Guide/Architecture-Overview.md', 'Developer Guide','Architecture Overview']
- ['Developer Guide/Data-Organization.md', 'Developer Guide','Data Organization']
- ['Developer Guide/File-Organization.md', 'Developer Guide','File Organization']
- ['Developer Guide/Development-Plans.md', 'Developer Guide','Development Plans']
- ['Developer Guide/_3rd-Party-Libraries.md', 'Developer Guide','3rd Party Libraries']
- ['Developer Guide/drivers/drivers.md', 'Developer Guide','Driver Reference']



