site_name: Sandbox Docs
repo_url: https://github.com/adlnet/SandboxDocs
site_favicon: favicon.ico
docs_dir : ./docs
theme: readthedocs
use_directory_urls: true
markdown_extensions: [admonition]
pages:
- ['index.md', 'About']
- ['Home.md', 'Home']
- ['Developer Guide/Developer-Guide.md', 'For Developers']
- ['FAQ.md', 'For Users', 'FAQ']
- ['User Guide/Using-The-Editor.md', 'For Users', 'Using The Editor']
- ['User Guide/Selecting-Objects.md', 'For Users', 'Selecting Objects']
- ['User Guide/Lights and Materials.md', 'For Users', 'Lights and Materials']
- ['User Guide/terrain.md', 'For Users', 'Terrain']
- ['User Guide/Cameras.md', 'For Users', 'Cameras']
- ['User Guide/Assets.md', 'For Users', 'Assets and Models']
- ['Developer Guide/Installation.md', 'Developer Guide','Installation']
- ['Developer Guide/Configuration.md', 'Developer Guide','Configuration']
- ['Developer Guide/Architecture-Overview.md', 'Developer Guide','Architecture Overview']
- ['Developer Guide/Data-Organization.md', 'Developer Guide','Data Organization']
- ['Developer Guide/File-Organization.md', 'Developer Guide','File Organization']
- ['Developer Guide/Development-Plans.md', 'Developer Guide','Development Plans']
- ['Developer Guide/SandboxAPI.md', 'Developer Guide','Sandbox API']
- ['Developer Guide/_3rd-Party-Libraries.md', 'Developer Guide','3rd Party Libraries']
- ['Developer Guide/drivers/Drivers.md', 'Developer Guide','Driver Reference']
- ['Developer Guide/Extending.md', 'Developer Guide','Extending Sandbox']





